### ISSUE TITLE
Implement a connection to firebase.

### ISSUE THREAD

**Issue by rordonez102** [rordonez102/finalprojtest#2]
The state of the chat messages persist but we want a way to store it in a database in case chat logs get lost in the process.

**Comment by rvincelee** [comment]
Created Firebase RTB and Firebase Storage to send chat messages that includes images.
![image](https://github.com/rordonez102/finalprojtest/assets/129351115/d31cf30d-0776-4355-b579-6989d71c805b)
![image](https://github.com/rordonez102/finalprojtest/assets/129351115/e946c914-bf68-4055-8ce8-2c20a6f3d588)
